import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/providers/providers";
import { Toaster } from "sonner";
import AuthGuard from "@/components/guard/Authguard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <AuthGuard>
            <Toaster
              position="top-center"
              richColors duration={500} closeButton
              style={{
                position: 'fixed', top: '50%', left: '50%', transform: 'translate(-50%, -0%)',
                zIndex: 9999,
              }}
            ></Toaster>
            {children}
          </AuthGuard>
        </AuthProvider>
      </body>
    </html>
  );
}
